// DO NOT EDIT THIS FILE -- it is automatically generated from googleai.go
// See the README file in this directory for additional details

package vertex

import (
	"context"
	"errors"
	"fmt"
	"iter"
	"log"
	"strings"

	"github.com/tmc/langchaingo/internal/util"
	"github.com/tmc/langchaingo/llms"
	"github.com/tmc/langchaingo/schema"
	"google.golang.org/genai"
)

var (
	ErrNoContentInResponse    = errors.New("no content in generation response")
	ErrUnknownPartInResponse  = errors.New("unknown part type in generation response")
	ErrInvalidMimeType        = errors.New("invalid mime type on content")
	ErrSystemRoleNotSupported = errors.New("system role isn't supporeted yet")
)

const (
	CITATIONS = "citations"
	SAFETY    = "safety"
	RoleModel = "model"
	RoleUser  = "user"
)

// Call implements the [llms.Model] interface.
func (g *Vertex) Call(ctx context.Context, prompt string, options ...llms.CallOption) (string, error) {
	return llms.GenerateFromSinglePrompt(ctx, g, prompt, options...)
}

// GenerateContent implements the [llms.Model] interface.
func (g *Vertex) GenerateContent(ctx context.Context, messages []llms.MessageContent, options ...llms.CallOption) (*llms.ContentResponse, error) {
	if g.CallbacksHandler != nil {
		g.CallbacksHandler.HandleLLMGenerateContentStart(ctx, messages)
	}

	opts := llms.CallOptions{
		Model:          g.opts.defaultModel,
		CandidateCount: g.opts.defaultCandidateCount,
		MaxTokens:      g.opts.defaultMaxTokens,
		Temperature:    g.opts.defaultTemperature,
		TopP:           g.opts.defaultTopP,
		TopK:           g.opts.defaultTopK,
	}
	for _, opt := range options {
		opt(&opts)
	}

	model, err := g.client.Models.Get(ctx, opts.Model, &genai.GetModelConfig{})
	if err != nil {
		return nil, err
	}

	var response *llms.ContentResponse

	if len(messages) == 1 {
		theMessage := messages[0]
		if theMessage.Role != schema.ChatMessageTypeHuman {
			return nil, fmt.Errorf("got %v message role, want human", theMessage.Role)
		}
		response, err = g.generateFromSingleMessage(ctx, model.Name, theMessage.Parts, &opts)
	} else {
		response, err = g.generateFromMessages(ctx, model.Name, messages, &opts)
	}
	if err != nil {
		return nil, err
	}

	if g.CallbacksHandler != nil {
		g.CallbacksHandler.HandleLLMGenerateContentEnd(ctx, response)
	}

	return response, nil
}

// convertCandidates converts a sequence of genai.Candidate to a response.
func convertCandidates(candidates []*genai.Candidate) (*llms.ContentResponse, error) {
	var contentResponse llms.ContentResponse

	for _, candidate := range candidates {
		buf := strings.Builder{}

		if candidate.Content != nil {
			for _, part := range candidate.Content.Parts {
				_, err := buf.WriteString(part.Text)
				if err != nil {
					return nil, err
				}
			}
		}

		metadata := make(map[string]any)
		metadata[CITATIONS] = candidate.CitationMetadata
		metadata[SAFETY] = candidate.SafetyRatings

		contentResponse.Choices = append(contentResponse.Choices,
			&llms.ContentChoice{
				Content:        buf.String(),
				StopReason:     string(candidate.FinishReason),
				GenerationInfo: metadata,
			})
	}
	return &contentResponse, nil
}

// convertParts converts between a sequence of langchain parts and genai parts.
func convertParts(parts []llms.ContentPart) ([]*genai.Part, error) {
	convertedParts := make([]*genai.Part, 0, len(parts))
	for _, part := range parts {
		var out *genai.Part

		switch p := part.(type) {
		case llms.TextContent:
			out = genai.NewPartFromText(p.Text)
		case llms.BinaryContent:
			out = genai.NewPartFromBytes(p.Data, p.MIMEType)
		case llms.ImageURLContent:
			typ, data, err := util.DownloadImageData(p.URL)
			if err != nil {
				return nil, err
			}
			out = genai.NewPartFromBytes(data, typ)
		}

		convertedParts = append(convertedParts, out)
	}
	return convertedParts, nil
}

// convertContent converts between a langchain MessageContent and genai content.
func convertContent(content llms.MessageContent) (*genai.Content, error) {
	parts, err := convertParts(content.Parts)
	if err != nil {
		return nil, err
	}

	c := &genai.Content{
		Parts: parts,
	}

	switch content.Role {
	case schema.ChatMessageTypeSystem:
		return nil, ErrSystemRoleNotSupported
	case schema.ChatMessageTypeAI:
		c.Role = RoleModel
	case schema.ChatMessageTypeHuman:
		c.Role = RoleUser
	case schema.ChatMessageTypeGeneric:
		c.Role = RoleUser
	case schema.ChatMessageTypeFunction:
		fallthrough
	default:
		return nil, fmt.Errorf("role %v not supported", content.Role)
	}

	return c, nil
}

// generateFromSingleMessage generates content from the parts of a single
// message.
func (g *Vertex) generateFromSingleMessage(ctx context.Context, model string, parts []llms.ContentPart, opts *llms.CallOptions) (*llms.ContentResponse, error) {
	convertedParts, err := convertParts(parts)
	if err != nil {
		return nil, err
	}

	config := &genai.GenerateContentConfig{
		MaxOutputTokens: int32(opts.MaxTokens),
		CandidateCount:  int32(opts.CandidateCount),
		StopSequences:   opts.StopWords,
	}
	if opts.Temperature >= 0 {
		temperature := float32(opts.Temperature)
		config.Temperature = &temperature
	}
	if opts.TopP >= 0 {
		topP := float32(opts.TopP)
		config.TopP = &topP
	}
	if opts.TopK >= 0 {
		topK := float32(opts.TopK)
		config.TopK = &topK
	}

	if opts.StreamingFunc == nil {
		// When no streaming is requested, just call GenerateContent and return
		// the complete response with a list of candidates.
		resp, err := g.client.Models.GenerateContent(ctx, model, []*genai.Content{genai.NewContentFromParts(convertedParts, genai.RoleUser)}, config)
		if err != nil {
			return nil, err
		}

		if len(resp.Candidates) == 0 {
			return nil, ErrNoContentInResponse
		}
		return convertCandidates(resp.Candidates)
	}
	iter := g.client.Models.GenerateContentStream(ctx, model, []*genai.Content{genai.NewContentFromParts(convertedParts, genai.RoleUser)}, config)

	return convertAndStreamFromIterator(ctx, iter, opts)
}

func (g *Vertex) generateFromMessages(ctx context.Context, model string, messages []llms.MessageContent, opts *llms.CallOptions) (*llms.ContentResponse, error) {
	history := make([]*genai.Content, 0, len(messages))
	for _, mc := range messages {
		content, err := convertContent(mc)
		if err != nil {
			return nil, err
		}
		history = append(history, content)
	}

	// Given N total messages, genai's chat expects the first N-1 messages as
	// history and the last message as the actual request.
	n := len(history)
	reqContent := history[n-1]
	history = history[:n-1]

	if reqContent.Role != RoleUser {
		return nil, fmt.Errorf("got %v message role, want user/human", reqContent.Role)
	}

	config := &genai.GenerateContentConfig{
		MaxOutputTokens: int32(opts.MaxTokens),
		CandidateCount:  int32(opts.CandidateCount),
		StopSequences:   opts.StopWords,
	}
	if opts.Temperature >= 0 {
		temperature := float32(opts.Temperature)
		config.Temperature = &temperature
	}
	if opts.TopP >= 0 {
		topP := float32(opts.TopP)
		config.TopP = &topP
	}
	if opts.TopK >= 0 {
		topK := float32(opts.TopK)
		config.TopK = &topK
	}

	chat, err := g.client.Chats.Create(ctx, model, config, history)
	if err != nil {
		return nil, err
	}

	var parts []genai.Part
	for _, part := range reqContent.Parts {
		parts = append(parts, *part)
	}

	if opts.StreamingFunc == nil {
		resp, err := chat.SendMessage(ctx, parts...)
		if err != nil {
			return nil, err
		}

		if len(resp.Candidates) == 0 {
			return nil, ErrNoContentInResponse
		}
		return convertCandidates(resp.Candidates)
	}
	iter := chat.SendMessageStream(ctx, parts...)

	return convertAndStreamFromIterator(ctx, iter, opts)
}

// convertAndStreamFromIterator takes an iterator of GenerateContentResponse
// and produces a llms.ContentResponse reply from it, while streaming the
// resulting text into the opts-provided streaming function.
// Note that this is tricky in the face of multiple
// candidates, so this code assumes only a single candidate for now.
func convertAndStreamFromIterator(ctx context.Context, it iter.Seq2[*genai.GenerateContentResponse, error], opts *llms.CallOptions) (*llms.ContentResponse, error) {
	candidate := &genai.Candidate{
		Content: &genai.Content{},
	}

	next, stop := iter.Pull2(it)
	defer stop()
DoStream:
	for {
		resp, err, hasNext := next()
		if !hasNext {
			break DoStream
		}
		if err != nil {
			log.Fatal(err)
		}

		if len(resp.Candidates) != 1 {
			return nil, fmt.Errorf("expect single candidate in stream mode; got %v", len(resp.Candidates))
		}
		respCandidate := resp.Candidates[0]

		if respCandidate.Content == nil {
			break DoStream
		}
		candidate.Content.Parts = append(candidate.Content.Parts, respCandidate.Content.Parts...)
		candidate.Content.Role = respCandidate.Content.Role
		candidate.FinishReason = respCandidate.FinishReason
		candidate.SafetyRatings = respCandidate.SafetyRatings
		candidate.CitationMetadata = respCandidate.CitationMetadata

		for _, part := range respCandidate.Content.Parts {
			if opts.StreamingFunc(ctx, []byte(part.Text)) != nil {
				break DoStream
			}
		}
	}

	return convertCandidates([]*genai.Candidate{candidate})
}
